global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AuthService
  - job_name: 'authservice'
    static_configs:
      - targets: ['authservice:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # MenuService
  - job_name: 'menuservice'
    static_configs:
      - targets: ['menuservice:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # KitchenService
  - job_name: 'kitchenservice'
    static_configs:
      - targets: ['kitchenservice:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # OrderService
  - job_name: 'orderservice'
    static_configs:
      - targets: ['orderservice:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s 