apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchenservice
  namespace: fasttech-foods
  labels:
    app: kitchenservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchenservice
  template:
    metadata:
      labels:
        app: kitchenservice
    spec:
      containers:
      - name: kitchenservice
        image: jpdevs/kitchenservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__MongoDb
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
        - name: KitchenSettings__DatabaseName
          value: "fasttech_kitchen"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kitchenservice-service
  namespace: fasttech-foods
spec:
  selector:
    app: kitchenservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
 