apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuservice
  namespace: fasttech-foods
  labels:
    app: menuservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuservice
  template:
    metadata:
      labels:
        app: menuservice
    spec:
      containers:
      - name: menuservice
        image: gustavoomacedo/menuservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__MongoDb
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
        - name: MenuSettings__DatabaseName
          value: "fasttech_menu"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: menuservice-service
  namespace: fasttech-foods
spec:
  selector:
    app: menuservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30003
  type: NodePort
 